# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDAY6VDuBRqEsvQMs4OGjx3f7_GEJpi1
"""

import pandas as pd
import numpy as np

data = pd.read_excel("/content/iris.xls")

print(data)

data.describe()

print(data.head())

print(data.columns)

print(data.mean(numeric_only=True))

print(data.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))
sns.histplot(data,kde=True)
plt.title('distribution of features')
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(data.select_dtypes(include=np.number).corr(),annot=True,cmap='coolwarm',linewidths=0.5) # Select only numerical features for correlation
plt.title('correlation heatmap')
plt.show()

sns.pairplot(data,hue=data.columns[-1])
plt.show()